name: "Deploy to GitHub Pages"

on:
  push:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linter
        run: npm run lint # Run your linter command here
      - name: Lint passed
        if: ${{ success() }}
        run: echo "Lint passed successfully!"

  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run SonarQube analysis
        run: echo "Running SonarQube analysis..." # Replace with actual SonarQube command

  deploy:
    needs: [lint, sonar]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy code to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
